### ISSUE TITLE
为什么做成服务化之后就报错？

### ISSUE THREAD

**Issue by killgcd4ever** [libraries/daze#27]
直接使用给定的例子，或者加上nohup启动都正常，但把daze服务化之后就报错，查看日志报以下错误：
panic: $HOME is not defined

goroutine 1 [running]:
log.Panicln(0xc00003dce0, 0x1, 0x1)
	C:/MyApp/go/src/log/log.go:347 +0xac
github.com/godump/ddir.Home(0x1007f7a77050dd8, 0x0)
	C:/Users/mohan/go/pkg/mod/github.com/godump/ddir@v0.0.0-20190322123919-4a9a295c6f75/go.go:48 +0x80
main.main()
	C:/src/daze/cmd/daze/main.go:42 +0x45

**Comment by killgcd4ever** [comment]
还有为什么设置了asheshadow加密方式指定混淆地址就不行呢，必须要设置成只ashe只加密不混淆才行

**Comment by mohanson** [comment]
1. Daze 会调用 https://github.com/godump/ddir/blob/master/go.go#L46 这个接口获取用户目录, 当你对其服务化时请确保 go 能正确获取用户目录.
2. 当设置 asheshadow 时, 服务端(daze server -e asheshadow)和客户端(daze client -e asheshadow)都需要同时指定使用该协议

**Comment by killgcd4ever** [comment]
感谢回复。
服务端和客户端都有设置asheshadow参数。混淆网站我指定的是自己服务器上的网站，同一台服务器，以为是这个问题，特地另外找了一个http协议的站点也不行，很奇怪，看日志也看不出啥名堂

**Comment by killgcd4ever** [comment]
go语言不是很懂，我是想做成systemd形式的服务，能不能给个例子？谢谢

**Comment by mohanson** [comment]
这是我目前在用的服务端和客户端的配置, 你可以试一下

**server**

```
daze server -e asheshadow -l 0.0.0.0:80 -m http://127.0.0.1:20001
```

**client**

```
daze client -s $SERVER:80 -e asheshadow -r https://raw.githubusercontent.com/mohanson/rule.ls/master/rule.ls -f auto
```

systemd 我没有写过, 我是用 supervisor 工具托管的.

**Comment by killgcd4ever** [comment]
好吧，谢谢您。希望您继续更新下去，支持你！

**Comment by killgcd4ever** [comment]
您好，能不能给下您supervisor配置如何编写的，我试了下仍然是报主楼提示的错误，以下是我的supervisor配置，请帮我看看有没有什么错误的地方：
[program:daze]
command=/usr/bin/daze server -l "0.0.0.0:80" -k "daze" -e "asheshadow" -m "http://xx.example.com"
directory=/usr/bin
priority=1
autostart=true
autorestart=true
startsecs=10
startretries=3
exitcodes=0
stopsignal=TERM
stopwaitsecs=10
stopasgroup=false
killasgroup=false
user=root
redirect_stderr=true
stdout_logfile=/var/log/daze/daze.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=10
stdout_capture_maxbytes=1MB
stdout_events_enabled=false

**Comment by killgcd4ever** [comment]
还有服务端混淆参数应该填域名还是http://ip:port的形式？我看你是后者。我nignx上有监听一个80端口的网站，但填上这个网站地址，始终连不上

**Comment by mohanson** [comment]
你配置 supervisor 的时候或者 systemd 的时候, 带上 HOME=/tmp 环境变量试试? 

服务端混淆只在 asheshadow 协议下有效, 可以是域名或 ip:port 形式. 服务端你直接输入 "daze server -e asheshadow -l 0.0.0.0:80 -m http://httpbin.org", 然后浏览器访问 80 端口也不行吗?

**Comment by killgcd4ever** [comment]
非常感谢回复，现在服务化完成了。还希望能以混淆的方式连接，我的服务端配置启动命令，如下：
/usr/bin/daze server -l "0.0.0.0:8880" -k "daze" -e "asheshadow" -m "http://mydomain.com"
客户端命令，如下：
daze.exe client -s "serverip:8880" -l "0.0.0.0:10080" -k "daze" -e "asheshadow" -f "auto" -dns "8.8.8.8:53"
服务端一直报：
read tcp serverip:8880->clientip:14161: use of closed network connection
浏览器提示connection aborted
能不能再帮忙解决下？
其实我服务器上有装nginx 配置了自己的网站，监听的是80端口，如果混淆网站我想配置成自己的站点，服务端和客户端应该如何设置？下面的配置我试了不行，启动报missing port   mydomain.com加上80端口又显然不行和nginx冲突
/usr/bin/daze server -l "mydomain.com" -k "daze" -e "asheshadow" -m "http://mydomain.com"
daze.exe client -s "mydomain.com" -l "0.0.0.0:10080" -k "daze" -e "asheshadow" -f "auto" -dns "8.8.8.8:53"

**Comment by mohanson** [comment]
1) 非混淆 (-e asheshadow) 情况可以正常跑么? 
2) 确认你服务器的时间与 PC 的时间相差在 2 分钟之内. 为了避免重放攻击, 协议内加入了时间戳并强制要求请求的时间戳差值在 2 分钟之内
3) 可以 nginx 改为监听 8888 端口, daze server 监听 80 端口并配置 -m http://127.0.0.1:8888
4) "-k" 是密钥, 建议不要用默认的 "daze"

**Comment by killgcd4ever** [comment]
1.非混淆，你指的是 -e ashe吧 这个是正常的 这个-m 是配置域名还是监听本地服务器地址加端口的形式？
2.服务器时间同步过
3.好的，我试试
4.哈，感谢指正
